CREATE TABLE USERS ( 
	USER_ID SERIAL PRIMARY KEY,
	USER_NAME VARCHAR(255) NOT NULL,
	USER_LASTNAME VARCHAR(255) NOT NULL,
	USER_EMAIL VARCHAR(255) NOT NULL,
	USER_PHONE VARCHAR(255) NOT NULL	
)

CREATE TABLE USERS_PASSWords(
	USER_ID integer NOT NULL,
	PASS_HESH VARCHAR(32) NOT NULL,
	CONSTRAINT FK_USER_ID_PASSWORD 
		FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
)

CREATE TABLE USERS_ADDRESSES(
	ADDRESS_ID SERIAL PRIMARY KEY,
	USER_ID integer NOT NULL,
	REGION VARCHAR(255) NOT NULL,
	CITY VARCHAR(255) NOT NULL,
	STREET VARCHAR(255) NOT NULL,
	HOUSE VARCHAR(255) NOT NULL,
	APARTMENT VARCHAR(255) NOT NULL,
	CONSTRAINT FK_USER_ID_ADDRESSES 
		FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
)

CREATE TABLE ORDERS(
	ORDER_ID SERIAL PRIMARY KEY,
	USER_ID integer NOT NULL,
	ORDER_DATE DATE NOT NULL,
	ORDER_STATUS VARCHAR(255) NOT NULL,
	ORDER_FULL_PRICE REAL NOT NULL,
	ORDER_DELIVER_TYPE VARCHAR(255) NOT NULL,
	ORDER_DELIVER_DATE DATE NOT NULL,
	CONSTRAINT FK_USER_ID_ORDERS
		FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
)

CREATE TABLE PRODUCTS(
	PRODUCT_ID SERIAL PRIMARY KEY,
	PRODUCT_NAME VARCHAR(511) NOT NULL,
	PRODUCT_BRAND VARCHAR(255) NOT NULL,
	PRODUCT_PRICE REAL NOT NULL,
	PRODUCT_AMOUNT INTEGER NOT NULL,
	PRODUCT_DESCRIPTION VARCHAR(1023) NOT NULL,
)

CREATE TABLE ORDERS_PRODUCTS(
	ORDER_ID integer NOT NULL,
	PRODUCT_ID INTEGER NOT NULL,
	PRODUCT_IN_ORDER_NUM INTEGER NOT NULL,
	CONSTRAINT FK_ORDER_ID_ORDERS_PRODUCTS
		FOREIGN KEY (ORDER_ID) REFERENCES,
	CONSTRAINT FK_PRODUCT_ID_ORDERS_PRODUCTS
		FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID)
)

CREATE TABLE PRODUCT_CHARACTERISTICS(
	PRODUCT_ID INTEGER NOT NULL,
	PROPERTY_ID INTEGER NOT NULL,
	PRODUCT_CHARACTERISTICS_VALUE VARCHAR(255) NOT NULL,
	CONSTRAINT FK_PRODUCT_ID_PRODUCT_CHARACTERISTICS
		FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID)
)

CREATE TABLE PRODUCT_GLOSSARY(
	PROPERTY_ID SERIAL PRIMARY KEY,
	PROPERTY_NAME VARCHAR(255) NOT NULL,
	CONSTRAINT FK_PROPERTY_ID_PRODUCT_GLOSSARY
		FOREIGN KEY (PROPERTY_ID) REFERENCES PRODUCT_CHARACTERISTICS(PROPERTY_ID)
)

CREATE TABLE PRODUCT_COMMENTS(
	COMMENT_ID SERIAL PRIMARY KEY,
	PRODUCT_ID INTEGER NOT NULL,
	USER_ID INTEGER NOT NULL,
	COMMENT_DATE DATE NOT NULL,
	COMMENT_TEXT VARCHAR(1023) NOT NULL,
	CONSTRAINT FK_USER_ID_PRODUCT_COMMENT
		FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
	CONSTRAINT FK_PRODUCT_ID_PRODUCT_COMMENT
		FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID)
)

CREATE TABLE BASKET(
	BASKET_ID SERIAL PRIMARY KEY,
	PRODUCT_ID INTEGER NOT NULL,
	USER_ID INTEGER NOT NULL,
	ADD_DATE DATE NOT NULL,
	CONSTRAINT FK_USER_ID_BASKET
		FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
	CONSTRAINT FK_PRODUCT_ID_BASKET
		FOREIGN	KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID)
)

CREATE TABLE FAVORITES(
	BASKET_ID SERIAL PRIMARY KEY,
	PRODUCT_ID INTEGER NOT NULL,
	USER_ID INTEGER NOT NULL,
	CONSTRAINT FK_USER_ID_FAVORITES
		FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
	CONSTRAINT FK_PRODUCT_ID_FAVORITES
		FOREIGN	KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID)
)